#!/usr/bin/env bash
set -euo pipefail

# Download DreamX-World-5B from ModelScope and place it in the layout expected
# by inference_ar_forcing.sh.
#
# The AR script reads:
#   MODEL_NAME=./Wan2.2-TI2V-5B
#   BASE_CHECKPOINT_PATH=/path/to/dreamx-world-5b.pt
#
# This script downloads the DreamX AR checkpoint repository to:
#   ./DreamX-World-5B/
# If a .pt/.pth checkpoint is found, it also creates:
#   ./DreamX-World-5B/baseline.pt
# and writes:
#   ./dreamx_ar_model.env
#
# Usage:
#   bash scripts/download_dreamx_world_5b_modelscope.sh
#   source dreamx_ar_model.env
#   bash inference_ar_forcing.sh

MODEL_ID="${MODEL_ID:-GD-ML/DreamX-World-5B}"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
MODEL_DIR="${MODEL_DIR:-${PROJECT_ROOT}/DreamX-World-5B}"
ENV_FILE="${ENV_FILE:-${PROJECT_ROOT}/dreamx_ar_model.env}"
PYTHON_BIN="${PYTHON_BIN:-python3}"

echo "=============================================="
echo "  Download DreamX-World-5B from ModelScope"
echo "=============================================="
echo "Model id:   ${MODEL_ID}"
echo "Model dir:  ${MODEL_DIR}"
echo "Env file:   ${ENV_FILE}"
echo "Python:     ${PYTHON_BIN}"
echo "=============================================="

mkdir -p "${MODEL_DIR}"

"${PYTHON_BIN}" - <<PY
import importlib.util
import os
import sys

if importlib.util.find_spec("modelscope") is None:
    raise SystemExit(
        "The 'modelscope' Python package is not installed. Install it first, for example:\\n"
        f"  {sys.executable} -m pip install -U modelscope"
    )

from modelscope import snapshot_download

model_id = os.environ.get("MODEL_ID", "${MODEL_ID}")
model_dir = os.environ.get("MODEL_DIR", "${MODEL_DIR}")

snapshot_download(
    model_id=model_id,
    local_dir=model_dir,
)
print(f"Downloaded {model_id} to {model_dir}")
PY

base_checkpoint_path="$(
  find "${MODEL_DIR}" -type f \( -name "*.pt" -o -name "*.pth" \) ! -path "*/.*/*" -printf "%s %p\n" \
    | sort -nr \
    | head -n 1 \
    | cut -d' ' -f2-
)"
checkpoint_path=""

if [[ -n "${base_checkpoint_path}" ]]; then
  baseline_link="${MODEL_DIR}/baseline.pt"
  if [[ "${base_checkpoint_path}" != "${baseline_link}" ]]; then
    ln -sfn "${base_checkpoint_path}" "${baseline_link}"
  fi
  checkpoint_for_env="${baseline_link}"
else
  checkpoint_path="$(
    find "${MODEL_DIR}" -type f -name "*.safetensors" ! -path "*/.*/*" -printf "%s %p\n" \
      | sort -nr \
      | head -n 1 \
      | cut -d' ' -f2-
  )"
  checkpoint_for_env="${checkpoint_path}"
fi

if [[ -z "${checkpoint_for_env}" ]]; then
  echo "ERROR: no checkpoint file (*.pt/*.pth/*.safetensors) found under ${MODEL_DIR}" >&2
  exit 1
fi

if [[ -n "${base_checkpoint_path}" ]]; then
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/download_dreamx_world_5b_modelscope.sh
export MODEL_NAME="${PROJECT_ROOT}/Wan2.2-TI2V-5B"
export BASE_CHECKPOINT_PATH="${checkpoint_for_env}"
export CHECKPOINT_PATH=""
EOF
else
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/download_dreamx_world_5b_modelscope.sh
export MODEL_NAME="${PROJECT_ROOT}/Wan2.2-TI2V-5B"
export BASE_CHECKPOINT_PATH=""
export CHECKPOINT_PATH="${checkpoint_for_env}"
EOF
fi

echo "=============================================="
echo "  Done"
echo "=============================================="
echo "Checkpoint: ${checkpoint_for_env}"
echo "Wrote env:  ${ENV_FILE}"
echo
echo "Next:"
echo "  source ${ENV_FILE}"
echo "  bash inference_ar_forcing.sh"
echo
echo "Note: MODEL_NAME points to ${PROJECT_ROOT}/Wan2.2-TI2V-5B."
echo "      Download Wan2.2-TI2V-5B there separately if it is not present yet."
