#!/usr/bin/env bash
set -euo pipefail

# Download both AR inference model repos from Hugging Face into the layout
# expected by inference_ar_forcing.sh:
#
#   ./Wan2.2-TI2V-5B/        text encoder, tokenizer, VAE
#   ./DreamX-World-5B/       DreamX AR checkpoint, baseline.pt
#
# Usage:
#   bash scripts/download_models_huggingface.sh
#
# Optional:
#   HF_TOKEN=... bash scripts/download_models_huggingface.sh
#   HF_MAX_WORKERS=16 bash scripts/download_models_huggingface.sh
#   HF_ENDPOINT=https://hf-mirror.com bash scripts/download_models_huggingface.sh

DREAMX_REPO_ID="${DREAMX_REPO_ID:-GD-ML/DreamX-World-5B}"
WAN_REPO_ID="${WAN_REPO_ID:-Wan-AI/Wan2.2-TI2V-5B}"
PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
DREAMX_DIR="${DREAMX_DIR:-${PROJECT_ROOT}/DreamX-World-5B}"
WAN_DIR="${WAN_DIR:-${PROJECT_ROOT}/Wan2.2-TI2V-5B}"
ENV_FILE="${ENV_FILE:-${PROJECT_ROOT}/dreamx_ar_model.env}"
VENV_DIR="${VENV_DIR:-${PROJECT_ROOT}/.venv}"
UV_BIN="${UV_BIN:-/root/.local/bin/uv}"

if [[ ! -x "${VENV_DIR}/bin/python" ]]; then
  echo "ERROR: Python virtualenv not found at ${VENV_DIR}" >&2
  echo "Create it first, or pass VENV_DIR=/path/to/.venv." >&2
  exit 1
fi

if [[ -f "${VENV_DIR}/bin/activate" ]]; then
  # shellcheck disable=SC1091
  source "${VENV_DIR}/bin/activate"
fi

PYTHON_BIN="${PYTHON_BIN:-${VENV_DIR}/bin/python}"
export HF_HUB_ENABLE_HF_TRANSFER="${HF_HUB_ENABLE_HF_TRANSFER:-1}"
export HF_MAX_WORKERS="${HF_MAX_WORKERS:-8}"

echo "=============================================="
echo "  Download DreamX + Wan from Hugging Face"
echo "=============================================="
echo "DreamX repo: ${DREAMX_REPO_ID}"
echo "Wan repo:    ${WAN_REPO_ID}"
echo "DreamX dir:  ${DREAMX_DIR}"
echo "Wan dir:     ${WAN_DIR}"
echo "Env file:    ${ENV_FILE}"
echo "Venv:        ${VENV_DIR}"
echo "Python:      ${PYTHON_BIN}"
echo "uv:          ${UV_BIN}"
echo "HF endpoint: ${HF_ENDPOINT:-https://huggingface.co}"
echo "Workers:     ${HF_MAX_WORKERS}"
echo "=============================================="

if ! "${PYTHON_BIN}" - <<'PY' >/dev/null 2>&1
import huggingface_hub
PY
then
  if [[ ! -x "${UV_BIN}" ]]; then
    echo "ERROR: huggingface_hub is not installed and uv was not found at ${UV_BIN}" >&2
    echo "Install manually with:" >&2
    echo "  ${PYTHON_BIN} -m pip install -U huggingface_hub hf_transfer" >&2
    exit 1
  fi
  echo "Installing Hugging Face download dependencies into ${VENV_DIR} ..."
  "${UV_BIN}" pip install --python "${PYTHON_BIN}" -U huggingface_hub hf_transfer
fi

if ! "${PYTHON_BIN}" - <<'PY' >/dev/null 2>&1
import hf_transfer
PY
then
  if [[ -x "${UV_BIN}" ]]; then
    echo "Installing hf_transfer for faster downloads ..."
    "${UV_BIN}" pip install --python "${PYTHON_BIN}" -U hf_transfer
  else
    echo "WARNING: hf_transfer is not installed; falling back to standard huggingface_hub downloads." >&2
    export HF_HUB_ENABLE_HF_TRANSFER=0
  fi
fi

mkdir -p "${DREAMX_DIR}" "${WAN_DIR}"

"${PYTHON_BIN}" - <<PY
import os
from huggingface_hub import snapshot_download

token = os.environ.get("HF_TOKEN") or None
max_workers = int(os.environ.get("HF_MAX_WORKERS", "8"))

downloads = [
    ("${WAN_REPO_ID}", "${WAN_DIR}"),
    ("${DREAMX_REPO_ID}", "${DREAMX_DIR}"),
]

for repo_id, local_dir in downloads:
    print(f"Downloading {repo_id} -> {local_dir}")
    snapshot_download(
        repo_id=repo_id,
        repo_type="model",
        local_dir=local_dir,
        token=token,
        max_workers=max_workers,
    )
    print(f"Finished {repo_id}")
PY

base_checkpoint_path="$(
  find "${DREAMX_DIR}" -type f \( -name "*.pt" -o -name "*.pth" \) ! -path "*/.*/*" -printf "%s %p\n" \
    | sort -nr \
    | head -n 1 \
    | cut -d' ' -f2-
)"
checkpoint_path=""

if [[ -n "${base_checkpoint_path}" ]]; then
  baseline_link="${DREAMX_DIR}/baseline.pt"
  if [[ "${base_checkpoint_path}" != "${baseline_link}" ]]; then
    ln -sfn "${base_checkpoint_path}" "${baseline_link}"
  fi
  base_checkpoint_for_env="${baseline_link}"
else
  checkpoint_path="$(
    find "${DREAMX_DIR}" -type f -name "*.safetensors" ! -path "*/.*/*" -printf "%s %p\n" \
      | sort -nr \
      | head -n 1 \
      | cut -d' ' -f2-
  )"
  base_checkpoint_for_env=""
fi

if [[ -z "${base_checkpoint_for_env}" && -z "${checkpoint_path}" ]]; then
  echo "ERROR: no DreamX checkpoint (*.pt/*.pth/*.safetensors) found under ${DREAMX_DIR}" >&2
  exit 1
fi

if [[ -n "${base_checkpoint_for_env}" ]]; then
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/download_models_huggingface.sh
export MODEL_NAME="${WAN_DIR}"
export BASE_CHECKPOINT_PATH="${base_checkpoint_for_env}"
export CHECKPOINT_PATH=""
EOF
else
  cat > "${ENV_FILE}" <<EOF
# Generated by scripts/download_models_huggingface.sh
export MODEL_NAME="${WAN_DIR}"
export BASE_CHECKPOINT_PATH=""
export CHECKPOINT_PATH="${checkpoint_path}"
EOF
fi

missing=0
for required in \
  "${WAN_DIR}/models_t5_umt5-xxl-enc-bf16.pth" \
  "${WAN_DIR}/Wan2.2_VAE.pth" \
  "${WAN_DIR}/google/umt5-xxl"; do
  if [[ ! -e "${required}" ]]; then
    echo "WARNING: expected Wan file or directory not found: ${required}" >&2
    missing=1
  fi
done

echo "=============================================="
echo "  Done"
echo "=============================================="
echo "Wan dir:       ${WAN_DIR}"
echo "DreamX dir:    ${DREAMX_DIR}"
echo "Env file:      ${ENV_FILE}"
if [[ -n "${base_checkpoint_for_env}" ]]; then
  echo "DreamX ckpt:   ${base_checkpoint_for_env}"
else
  echo "DreamX ckpt:   ${checkpoint_path}"
fi
if [[ "${missing}" -eq 0 ]]; then
  echo "Required Wan base-model files are present."
else
  echo "Download completed, but one or more expected Wan files were not found."
  echo "Please inspect ${WAN_DIR} before running inference."
fi
echo
echo "Next:"
echo "  source ${VENV_DIR}/bin/activate"
echo "  source ${ENV_FILE}"
echo "  bash inference_ar_forcing.sh"
